import type { SectionContent } from '../types';

export const content: SectionContent = {
  slug: 'compliance',
  title: 'Industry Compliance',
  description:
    'How AI agent identity and authorization requirements map to HIPAA, SOX, FINRA, the EU AI Act, FedRAMP, NIST, and multi-tenant data privacy frameworks — and why shared service accounts create audit and regulatory exposure.',
  tags: ['compliance', 'hipaa', 'sox', 'finra', 'fedramp', 'nist', 'gdpr', 'pci-dss', 'eu-ai-act', 'multi-tenant'],
  icon: '⚖️',
  hasDiagram: false,
  diagramPrompt: '',
  cards: [
    {
      heading: 'Healthcare: HIPAA',
      paragraphs: [
        'The HIPAA Minimum Necessary Standard requires that access to Protected Health Information be limited to the minimum necessary to accomplish the intended purpose. For AI agents this is a technical enforcement requirement, not an assumed behavior. A service account granted broad patient record access violates the Minimum Necessary Standard even if the agent only queries what it needs during normal operation — because the technical permission boundary permits far more than that. Auditors examine what the credential can do, not what it typically does. An agent identity with narrowly scoped, per-request tokens satisfies the standard in a way that a shared broad-access service account structurally cannot.',
        'HIPAA Security Rule section 164.312(b) mandates that covered entities implement hardware, software, and procedural mechanisms to record and examine activity in information systems containing PHI. Every PHI access must be logged with specific identity, what was accessed, when, and from where. Shared service accounts collapse this requirement entirely — the audit log shows the service account, not the individual user or clinical context that authorized the access. When a clinical AI agent queries patient records using a shared EHR service account, there is no patient-specific scope control and no way to reconstruct which clinician authorized which query. This is a structural audit gap, not a configuration problem.',
        'Okta, both Workforce Identity Cloud and Auth0, is a HIPAA Business Associate with a Business Associate Agreement available. AI agent infrastructure handling PHI must be covered under a BAA — this is a precondition for compliant deployment, not an optional enhancement. Organizations deploying clinical AI should verify BAA coverage for every component in the agent infrastructure chain, including the identity provider. The practical implication is that Auth0 enterprise customers in healthcare have a path to compliant agentic deployment through the Auth0 BAA, while organizations using unverified identity infrastructure have a compliance gap regardless of their application-layer controls.',
        'A documented real-world pattern from hospital deployments illustrates the exposure. A clinical documentation agent was deployed using a shared EHR service account to query patient records for note generation. During a HIPAA audit, investigators found that the audit logs showed only the service account identifier with no patient-specific scope control and no clinician attribution. The agent had accessed hundreds of patient records over weeks with no log trail showing who authorized each access. The result was a breach notification obligation and a civil monetary penalty. The discovery question for SEs is direct: when your clinical AI reads a patient record, does the audit log show the patient ID and the authorizing clinician, or does it show a service account?',
      ],
    },
    {
      heading: 'Financial Services: SOX, FINRA, EU AI Act',
      paragraphs: [
        'SOX IT General Controls require that access changes to financial systems produce audit evidence equivalent to what a human administrator would generate. As of 2025 and 2026, SOX auditors are specifically examining whether AI agents that automate access changes, financial data queries, or reporting workflows have unique, audited identities. An AI agent with a shared service account credential produces audit evidence attributable only to that service account — it satisfies the logging requirement on paper while eliminating the accountability the requirement was designed to enforce. The practical question auditors are asking is whether you can demonstrate that a specific agent action was authorized by a specific human principal at a specific time. Shared credentials make that answer no by design.',
        'FINRA Regulatory Notice 24-09, published in 2024, addressed the use of AI in securities trading and operations. Firms using AI in trading workflows are required to document governance frameworks that include access controls and audit trails. The Notice treats AI governance as an extension of existing supervision obligations — not a new regulatory category, but an application of existing rules to a new class of actor. An agent executing trading operations without a documented identity and access governance framework is non-compliant with supervision requirements regardless of whether the underlying trades are sound. The audit trail for algorithmic and AI-assisted trading must be able to attribute each action to an authorized system with documented controls.',
        'The EU AI Act, with enforcement beginning in 2025 and 2026, classifies AI systems used in credit, employment, essential services, and law enforcement as high-risk. High-risk AI systems require human oversight mechanisms — CIBA (Client-Initiated Backchannel Authentication) is a technical implementation of this requirement, enabling human approval gates for agent actions before execution. The Act also requires audit logging and transparency such that decisions made by AI systems can be attributed and explained. Black-box agent actions that cannot be attributed to a specific identity and authorization chain will fail EU AI Act compliance review. MiFID II adds a further layer for algorithmic trading systems, requiring registration, documented risk controls, and governance — an agent executing trading logic must have an auditable identity that can be presented to regulators on demand.',
        'The SE talking point for financial services prospects is grounded in what their auditors are already doing. SOX auditors want IT General Controls on AI agents structured the same way they want controls on human admins — unique identity, access review, and deprovisioning. FINRA and the SEC are examining AI in trading workflows under existing supervision rules. The EU AI Act requires documented human oversight for high-risk AI that will be tested in enforcement actions starting now. The current state for most firms is that their agents run as shared service accounts — that is a compliance gap that will surface in the next audit cycle, not a hypothetical future risk.',
      ],
    },
    {
      heading: 'Government: FedRAMP and NIST',
      paragraphs: [
        'FedRAMP authorization is a prerequisite for any cloud service used by US federal agencies. Okta Workforce Identity Cloud Government Cloud is FedRAMP Moderate authorized, which means it satisfies the authorization requirement for federal AI agent deployments. Auth0 does not have FedRAMP authorization. This is not a configuration gap or a roadmap item — it is a current authorization status that eliminates Auth0 as an option for federal customers deploying AI agents in FedRAMP-scoped environments. When federal prospects are evaluating Okta for agentic deployments, the FedRAMP status of WIC Government Cloud is a qualification criterion, not a differentiator.',
        'NIST Special Publication 800-53 Access Control family control AC-2 requires that all accounts, including non-human identities, be inventoried with assigned owners, subject to periodic access reviews, and promptly deprovisioned when no longer needed. AI agents are non-human identities that must be managed under AC-2 the same way human accounts are managed. An AI agent with no assigned owner, no inventory record, and no deprovisioning process is an AC-2 finding. The control requires that organizations know what accounts exist, who is responsible for them, and whether they should still have access — none of which is possible for agent identities managed as anonymous shared service accounts.',
        'NIST 800-53 control IA-3 requires that devices and systems be uniquely identified and authenticated before establishing connections. AI agents that share credentials with other systems or with human operators fail IA-3 because they cannot be uniquely identified at the authentication layer. The Okta Non-Human Identity model addresses IA-3 directly by issuing unique, machine-specific credentials to each agent identity — the agent authenticates as itself, not as a shared pool credential. This makes each agent\'s actions attributable to a unique authenticated entity at the infrastructure level, not just at the application level.',
        'The NIST AI Risk Management Framework structures AI governance around four functions: GOVERN, MAP, MEASURE, and MANAGE. The GOVERN function addresses organizational accountability and ownership for AI systems — Okta NHI provides the ownership and accountability infrastructure for agent identities. The MANAGE function addresses incident response and risk treatment, including the ability to revoke or modify AI system access during an incident — Okta\'s centralized identity model enables rapid revocation of agent credentials without modifying application code. The MEASURE function requires audit and assessment capabilities to evaluate AI system behavior — Okta\'s audit logging for agent token issuance and access events provides the measurement data the RMF requires. Federal and regulated agency customers building AI systems should expect their AI governance documentation to map to RMF functions, and each function has a direct Okta product mapping.',
      ],
    },
    {
      heading: 'SaaS Multi-Tenant and Data Privacy',
      paragraphs: [
        'Multi-tenant SaaS applications face an agent isolation requirement that is structurally different from single-tenant deployments. When the same agent infrastructure serves multiple tenants, each request must be scoped so that the agent can only access data belonging to the tenant whose request it is currently processing. This isolation must be cryptographically enforced through the token and authorization layer — it cannot be enforced solely by application logic, because application logic errors, prompt injection attacks, or agent state confusion can cross tenant boundaries if the credential itself is not tenant-scoped. A single service account with access to all tenant data is a multi-tenant isolation failure regardless of how careful the application code is.',
        'Auth0 Fine Grained Authorization with multi-tenancy implements tenant-scoped authorization through relationship tuples that encode which identities have which permissions on which resources within which tenant context. When an agent queries FGA with the current tenant context, it receives authorization decisions that are bounded to that tenant\'s data. A misrouted request or a prompt injection attempt to access another tenant\'s records fails at the authorization layer rather than at the application layer. The cryptographic binding of the token to a tenant context means that even a compromised or confused agent cannot escape the authorization boundary established at token issuance.',
        'SOC 2 Type II Confidentiality trust service criteria require that information designated as confidential be protected as committed. For multi-tenant SaaS, each tenant\'s data is confidential relative to other tenants. An AI agent serving multiple tenants via a single shared service account fails the Confidentiality criteria because there is no technical control preventing cross-tenant data access — the credential boundary does not align with the confidentiality boundary. SOC 2 auditors examining agentic systems will test whether tenant data isolation is enforced at the identity and authorization layer, not just the application layer. GDPR adds a further obligation: data subjects have the right to access records of processing activities, including AI-mediated access to their personal data. An agent that accesses personal data through a shared credential cannot produce per-subject access records.',
        'PCI DSS requires that access to cardholder data be attributable to individual user accounts, with no shared credentials permitted in cardholder data environments. An AI agent performing payment operations — fraud detection, transaction processing, chargeback review — using shared service account credentials fails PCI DSS section 8 requirements on unique IDs and section 10 requirements on audit trail attribution. CCPA grants California consumers the right to know what categories of third parties and automated systems have accessed their personal information. An organization that cannot attribute AI agent access to specific identifiable system actors cannot satisfy CCPA right-to-know requests for AI-mediated data access. CCPA and GDPR together create a de facto requirement that any AI system touching consumer personal data have an attributable, auditable identity — which is the same technical requirement as HIPAA, SOX, and FedRAMP, applied to the consumer privacy context.',
      ],
    },
  ],
};
