import type { SectionContent } from '../types';

const slug = 'competitive';
const title = 'Competitive Intel';
const description =
  'How Okta O4AA compares to Microsoft Entra, AWS IAM, Ping Identity, CyberArk, SailPoint, and the broader March 2026 landscape shift toward agent runtime identity.';
const tags = ['competitive', 'microsoft', 'aws', 'ping', 'cyberark', 'sailpoint', 'agentic-ai'];
const icon = '🏁';
const hasDiagram = false;
const diagramPrompt = '';

const cards = [
  {
    heading: 'Microsoft Entra — Zero Trust for AI and Recent Incidents',
    image: 'diagrams/competitive-entra.png',
    paragraphs: [
      'Microsoft Entra (formerly Azure AD) is the incumbent identity layer across most enterprise environments. It is a formidable competitor due to sheer distribution: Entra ID is included in Microsoft 365 E3/E5 licenses at effective zero incremental cost. CFO-driven "Microsoft-only" consolidation is the most common reason Okta loses to Entra, not feature parity.',
      'In March 2026 Microsoft announced "Zero Trust for AI" and new agentic AI security capabilities spanning Entra, Defender, and Purview. This is a coordinated messaging campaign, not a single product launch. The framing ties Copilot governance, Purview data classification, and Entra Workload Identities into a single narrative. Expect prospects to have heard of it before your call.',
      '!! The core architectural gap for agentic workloads: Entra On-Behalf-Of (OBO) flow requires a user-initiated token as the starting point. Autonomous agents running on client credentials cannot generate OBO tokens that carry delegated user identity. In any agentic scenario where the human authorized an action before the agent executes it — which is most of them — Entra has no native mechanism to propagate that delegation through the chain.',
      '!! Device trust is under active scrutiny. In March 2026, CISA issued a warning that attackers successfully abused Microsoft Intune to wipe devices during the Stryker cyberattack. This follows the September 2025 critical Entra ID flaw that allowed Global Admin impersonation across tenants. Any prospect citing Entra as their security baseline should be walked through these incidents.',
      '?? Discovery: "How does Entra maintain user-level audit trails when an autonomous agent — not a human — is the one making the downstream API call? Which user does CloudTrail log in that scenario?" This surfaces the delegation gap immediately.',
      '?? Discovery: "How are you managing identity for AI agents that need to call non-Microsoft SaaS — Salesforce, ServiceNow, Workday — where Managed Identities have no reach?" Entra Managed Identities are Azure-scoped. Multi-cloud agents fall back to secrets or custom engineering.',
      'TT Objection response for "We already have Entra E5": "Entra E5 is the right answer for your Azure workloads. The gap is the cross-cloud, cross-SaaS delegation layer — who the agent is acting for, across every API it touches, with a single audit trail. That is not a problem Entra was designed to solve, and it is the exact problem O4AA is built for."',
      'On provisioning: Okta enhanced its O365 provisioning controls in March 2026 to allow attribute sync without overwriting licenses and roles managed natively in Microsoft. This prevents costly licensing errors that Microsoft\'s own native tools obscure. Use this in M365-heavy accounts where both products will coexist.',
    ],
  },
  {
    heading: 'AWS IAM — Bedrock Agents, STS Limits, and the User Delegation Gap',
    image: 'diagrams/competitive-aws.png',
    paragraphs: [
      'AWS IAM is the correct tool for authenticating agents to AWS infrastructure. IAM Roles for Compute (EC2, Lambda, ECS, SageMaker) provision temporary credentials automatically. STS AssumeRole handles cross-account and cross-service delegation with role chaining. For agents running entirely within the AWS ecosystem operating on AWS resources, this is a well-solved problem. The conversation starts when agents leave the AWS boundary.',
      '!! The Bedrock Agents user identity gap is the decisive technical point. Bedrock Agents assign a single IAM service role per agent. Every user request — regardless of which human initiated it — executes under that same role. CloudTrail logs the service role ARN, not the individual user who triggered the action. Per-user data access control and user-level audit trails require custom engineering completely outside IAM. There is no native STS mechanism to propagate user identity through an agent chain.',
      '!! AWS IAM has no user delegation primitive. STS AssumeRole, IAM Roles Anywhere, and Outbound Identity Federation all operate at the workload level. None of them carry "this action is on behalf of user@company.com with these scopes for this session window." RFC 8693 Token Exchange — the standard mechanism for this pattern — is not a supported construct in AWS IAM.',
      'IAM complexity is a real operational cost. The JSON policy language is notoriously error-prone and AWS released IAM Policy Autopilot (an AI coding assistant) in December 2025 specifically to help developers write policies correctly. The existence of the tool is a good landmine: it signals that AWS itself acknowledges the complexity is a barrier.',
      '?? Discovery: "When a Bedrock agent takes an action on behalf of a user, what does your CloudTrail log as the principal? Can you demonstrate per-user data access enforcement — where user A\'s agent cannot read user B\'s data — without custom code outside IAM?"',
      '?? Discovery: "Your Bedrock agents will eventually need to call your CRM, your ticketing system, your internal APIs. How are those credentials managed today, and what happens when a secret rotates?"',
      'TT Objection response for "We\'re AWS-native, we\'ll just use IAM": "IAM handles your agent\'s identity to AWS services perfectly — we are not replacing that. The gap is the layer above it: which user authorized this agent, what scope they granted, and the audit trail that connects every downstream action back to that human decision. IAM was never designed for that layer. O4AA is."',
      'Positioning note: In practice this is rarely a head-to-head displacement. The target architecture is Okta as the human delegation and cross-SaaS authorization layer, with AWS IAM handling AWS-scoped infrastructure access downstream — federated from Okta via IAM Identity Center.',
    ],
  },
  {
    heading: 'Ping Identity — "Identity for AI" GA and the Runtime Identity Challenge',
    image: 'diagrams/competitive-ping.png',
    paragraphs: [
      'Ping Identity is the most direct new competitor in the agentic identity space as of March 2026. On March 25 they announced "Identity for AI" reaching General Availability on March 31. This is not a roadmap item — it is a shipping product and prospects in active RFPs will have seen it. You must be prepared to address it specifically.',
      'Ping\'s "Identity for AI" introduces what they call Runtime Identity: a framework that registers autonomous AI agents as users in PingOne, links them to a human owner, and enforces delegated, fine-grained access controls at every action the agent takes. The concept maps directly to O4AA\'s agent delegation model. The key differences are architecture, ecosystem, and deployment reality.',
      '!! Ping\'s Runtime Identity is built on PingOne (cloud) and PingFederate (on-prem/hybrid) — two platforms that operate differently and require separate administrative consoles. An enterprise deploying Runtime Identity in a hybrid environment is inheriting two upgrade tracks, two support contracts, and the fragmentation Ping has been managing since the ForgeRock acquisition in August 2023. Okta O4AA is a single SaaS control plane.',
      '!! Financial health is a legitimate risk signal. Thoma Bravo had to refinance Ping\'s debt in October 2025 to reduce interest payments — a move that signaled financial pressure on the PE-owned company. Prospects in regulated industries with long procurement cycles should evaluate vendor stability, not just feature parity.',
      'Ping does have genuine strengths in this space. PingFederate supports token exchange including OBO flows. PingAuthorize is an externalized authorization engine comparable in concept to Okta FGA. Their October 2025 Keyless acquisition added Zero-Knowledge Biometrics for privacy-preserving authentication. In February 2026 their Secure Containers were approved for Iron Bank, making them very strong in DoD/IL5 environments. If the deal is Federal or DoD-adjacent, treat Ping as a serious incumbent.',
      '?? Discovery: "Identity for AI sounds like it solves the same problem as O4AA. Walk me through how Runtime Identity handles a scenario where an agent needs to act on behalf of a user in your non-Ping SaaS applications — where PingFederate is not in the call path. What enforces the delegation there?"',
      '?? Discovery: "How many products from the Ping portfolio — PingOne, PingFederate, PingAccess, PingAuthorize — are involved in a full Runtime Identity deployment? Who owns the integration between them when something breaks?"',
      'TT Objection response for "Ping just launched the same thing": "Ping launched Runtime Identity for their ecosystem. The question is what happens when your AI agents operate across your entire SaaS footprint — including apps that Ping does not have pre-built integrations for. Okta O4AA sits above any IdP, including Ping, as the delegation and audit layer. You can run both."',
      'TT Objection response for "We already have PingFederate on-prem": "PingFederate is your federation engine — it is not going away today. The agentic identity question is what sits above it to govern what your AI agents are authorized to do on behalf of your users, across every system they touch. That is the layer Okta adds without requiring a rip-and-replace."',
    ],
  },
  {
    heading: 'CyberArk and SailPoint — Diverging Bets in the AI Era',
    paragraphs: [
      'CyberArk and SailPoint are both making aggressive AI identity plays but from very different positions, and both face structural limitations that create clear Okta differentiation.',
      'CyberArk closed a $25 billion acquisition by Palo Alto Networks in February 2026. Within days, PANW cut over 500 CyberArk jobs. The acquisition makes CyberArk a pillar within the PANW platformization strategy — their trajectory is now tied to PANW\'s "Precision AI" narrative, and they are no longer a neutral identity vendor. Prospects looking for an independent identity control plane above all network and cloud providers should be aware of this dependency.',
      '!! CyberArk\'s AI agent strategy is PAM-centric: vault the agent\'s credentials, attest the workload, manage privilege escalation. This is the right model for securing agents\' own secrets. It does not address the user delegation layer — which human authorized the agent, what scope, and whether that authorization is still valid at runtime. CyberArk is not investing heavily in runtime identity for autonomous agents in the sense of cross-SaaS user delegation. This is a meaningful gap when the prospect\'s AI agents need to act on behalf of end users, not just access infrastructure.',
      'CyberArk is openly pivoting toward Operational Technology (OT) for manufacturing environments and PKI/TLS certificate lifecycle management. These are greenfield markets for them. Expect CyberArk to be less aggressive in pure AI agent RFPs and more focused on manufacturing, industrial, and infrastructure accounts. In those accounts they are the right PAM layer; Okta O4AA is the user delegation layer above it.',
      'SailPoint is a different kind of competitor. They hit $1.1 billion in FY26 revenue, and in March 2026 they launched "Shadow AI Remediation" to address unsanctioned GenAI usage. They also signed a strategic collaboration with AWS to govern agentic AI workloads. On paper this sounds directly competitive. In practice SailPoint is a governance engine — they can detect and report that shadow AI exists, but they rely on an Access Management vendor to actually terminate the session or enforce the policy inline.',
      '!! SailPoint\'s stock plunged 22% to a 12-month low in March 2026 following a weak Q1 FY26 and FY27 revenue forecast. Despite the top-line revenue, the market is pricing in execution risk on their ambitious expansion into PAM, observability, and AI governance. This is live FUD for deals in progress: prospects in long procurement cycles with SailPoint are exposed to vendor risk at a critical moment.',
      '?? Discovery for CyberArk accounts: "When an autonomous AI agent takes an action in your environment, CyberArk can tell you what credentials the agent used. Can it tell you which human user authorized the agent to take that action, and whether that authorization has been revoked since it was granted?"',
      '?? Discovery for SailPoint accounts: "SailPoint\'s Shadow AI Remediation can surface that unsanctioned AI usage is happening. When it identifies a violation, what enforcement mechanism actually terminates that active session? Who owns that enforcement layer in your current stack?"',
      'TT Objection response for CyberArk: "CyberArk solves the secrets and privilege problem — that is genuine value and it belongs in the stack. Okta O4AA solves the delegation problem that sits above it: who the agent is acting for, what they are authorized to do, and the immutable audit trail from human decision to agent action."',
      'TT Objection response for SailPoint: "SailPoint governs access policy and can detect Shadow AI. Okta enforces it at the authentication event. These products are designed to work together — OIG and SailPoint solve the same governance layer, but the real-time enforcement and user delegation for AI agents happens in O4AA, at the moment of token issuance."',
    ],
  },
  {
    heading: 'Market Landscape — The March 2026 Shift and Where Okta Stands',
    image: 'diagrams/competitive-landscape.png',
    paragraphs: [
      'March 2026 marks the point at which agentic AI identity moved from a roadmap conversation to an RFP disqualification criterion. Microsoft, Ping Identity, SailPoint, and Okta all launched dedicated AI agent security frameworks within a 30-day window. Vendors without a runtime identity story for autonomous agents are being removed from enterprise shortlists before the first demo.',
      '!! The defining question in every competitive RFP right now is: "Can your platform maintain user-level delegation through an autonomous agent chain, enforce fine-grained access per action, and produce a human-traceable audit trail — without requiring the agent to be Azure-native, AWS-native, or on-Ping?" This is the question that eliminates Microsoft (Azure-locked Managed Identities), AWS (no user delegation primitive in STS), and Ping (hybrid fragmentation) and that O4AA was designed to answer.',
      'IAM platforms are absorbing CASB capabilities. The simultaneous launch of Shadow AI discovery tools by SailPoint and Okta signals that identity platforms are taking over application discovery workloads previously owned by network security and CASB vendors. Buyers evaluating CASB renewals should be shown Okta\'s Shadow AI discovery capabilities as a consolidation play.',
      'CyberArk\'s pivot to OT and PKI is a strategic retreat from the AI agent conversation. By moving into manufacturing identity and certificate lifecycle management, they are choosing greenfield markets over competing directly against Okta and Ping in software-defined agentic security. In IT-focused accounts, this reduces CyberArk from a head-to-head competitor to a complementary PAM layer.',
      'SailPoint\'s financial turbulence creates a specific opportunity. Their 22% stock drop and weak FY27 guidance are not public knowledge for every prospect, but they are easily surfaced. In deals where SailPoint is the incumbent IGA vendor, the question of whether to expand with SailPoint\'s new AI governance modules (at a financially vulnerable company) versus consolidating on Okta Identity Governance + O4AA is a legitimate strategic framing.',
      'Microsoft\'s reputational damage from the CISA/Stryker incident is the most immediate opportunity in the field. CISA explicitly called out Intune as the attack vector used to wipe devices in a major breach. Any prospect running Intune as their device trust anchor for AI agent access policies is a live displacement conversation for Okta\'s Enhanced Disaster Recovery and phished-resistant device posture model.',
      '?? Board-level discovery question: "Which of your AI agent initiatives require an agent to act on behalf of a specific user — accessing that user\'s data, triggering actions in that user\'s name? How are you tracking authorization provenance for those actions today, and who owns the audit trail if a regulator asks?"',
      '?? Architecture question: "If your AI agents need to call five different SaaS platforms — none of them AWS, none of them Azure-native — which identity layer today provides unified token issuance, scoped delegation, and a single audit log across all five?"',
      'TT Positioning statement for competitive deals: "Every major vendor launched an AI identity story this month. The difference is architecture. Microsoft secures Copilot. Ping secures their PingOne ecosystem. SailPoint governs the policy. CyberArk vaults the secrets. Okta O4AA is the delegation layer that sits above all of them — cloud-agnostic, user-traceable, enforcement-ready at token issuance, across every API your agents touch. That is not a feature. That is the missing layer in every one of those architectures."',
      '>> Okta\'s March 2026 counter-offensive: "Okta for AI Agents" blueprint published, Auth0 partnership with Yubico and IBM announced for hardware-backed human governance of AI actions, Shadow AI discovery launched in February, Enhanced Disaster Recovery (1-hour RTO, self-service failover APIs) launched in March, and enhanced O365 provisioning controls released. This is the most concentrated Okta product launch window in recent memory. Use all of it.',
    ],
  },
  {
    heading: 'Emerging Competitors — NHI Startups and Developer-First Auth',
    paragraphs: [
      'A wave of well-funded startups is targeting the AI agent identity space from below. These companies are not displacing Okta at the enterprise level — but they are capturing developer mindshare and POC wins in engineering-led evaluations. SEs will increasingly encounter them in technical evaluations.',
      '!! Astrix Security launched the industry\'s first "AI Agent Control Plane" (ACP) — a purpose-built platform for discovering, monitoring, and governing AI agent identities. At $25M revenue with 123 employees, Astrix is the most mature NHI-focused startup. Their shadow AI agent discovery directly competes with Okta ISPM. Strength: pure-play focus on non-human identity means faster iteration. Weakness: no human identity, no SSO, no OBO — they solve governance but not the auth layer.',
      '!! Oasis Security raised a massive $120M Series B in March 2026 (Sequoia, Accel, Craft Ventures) for "Agentic Access Management." This is the largest funding round in the NHI space and signals serious VC conviction. Oasis focuses on agent identity lifecycle — inventory, posture assessment, and remediation. Like Astrix, they cover governance without providing the auth mechanism. Watch for: they may acquire or build auth capabilities with this funding.',
      'Aembit ($25M Series A) focuses on workload-to-workload identity — secretless access between services using ephemeral credentials. Directly competes with Token Vault for the credential management layer. Their approach: agents authenticate using platform attestation (Kubernetes service account, AWS IAM role) and Aembit issues short-lived credentials to downstream services. Strength: cloud-native, zero-secret approach. Weakness: no user delegation (OBO), no FGA, no MCP support.',
      'Stytch (acquired by Twilio, November 2025) is pivoting from developer CIAM to AI agent auth. They launched OAuth Client ID Metadata Document (CIMD) support for MCP clients — the same spec the Okta MCP Adapter uses. As part of Twilio, they have distribution through Twilio\'s developer ecosystem. Descope ($88M seed, Lightspeed) claims "Identity Governance for AI Agents" and is building MCP-native auth flows. Both target developer-first organizations that haven\'t chosen an enterprise IdP yet.',
      '>> Silverfort takes a different approach entirely: an agentless overlay that extends MFA and conditional access to legacy systems without code changes. Relevant when AI agents need to authenticate to systems that don\'t support modern auth (mainframes, legacy databases, on-prem apps). Silverfort is complementary to Okta for the legacy access path — not competitive for the core agent identity layer.',
      'TT When you encounter these companies in deals: "These startups solve real problems — shadow agent discovery, NHI governance, secretless workload auth. What they don\'t have is the identity platform underneath: no SSO, no OBO Token Exchange, no FGA, no MCP Adapter, no System Log audit trail. They\'re governance overlays that need an identity foundation. Okta IS that foundation. The question isn\'t Okta vs. Astrix — it\'s whether the customer needs Okta alone, or Okta plus a governance overlay."',
      '?? Is the customer evaluating any NHI-specific vendors? If so, position Okta as the auth layer those vendors depend on — not as a competitor to them. The expansion path: Okta for agent auth + the NHI vendor for governance visibility. Both land, Okta owns the auth decision.',
    ],
  },
];

export const content: SectionContent = { slug, title, description, tags, icon, hasDiagram, diagramPrompt, cards };
