import type { SectionContent } from '../types';

export const content: SectionContent = {
  slug: 'security',
  title: 'Security Threats & Mitigations',
  description:
    'The security attack surface unique to AI agentic systems — confused deputy attacks, prompt injection, token leakage, and how Okta\'s authorization model mitigates each threat category.',
  tags: ['security', 'threats', 'prompt-injection', 'minimal-privilege', 'token-security'],
  icon: '🛡️',
  hasDiagram: false,
  diagramPrompt: '',
  cards: [
    {
      heading: 'Confused Deputy Attack',
      paragraphs: [
        'A confused deputy attack in the AI agent context occurs when an agent is tricked into using its elevated permissions to perform an action it was not supposed to perform — acting as an unwitting intermediary between an attacker and a privileged API. The "deputy" is the AI agent; the "confusion" is induced by malicious content that the agent processes as part of its normal task, such as text embedded in a webpage, a document, or a database result. Because the agent has legitimate credentials, the API it calls cannot distinguish the malicious request from a legitimate one — the authorization looks valid at the perimeter, but the underlying intent was attacker-controlled.',
        'A concrete example illustrates the risk. An AI agent has been granted access to a corporate email API with the scope to send messages on behalf of a user. The agent is tasked with summarizing news articles from external websites. One of the articles contains injected text — invisible to a human reader but visible to the agent — instructing it to forward the user\'s last 100 emails to an external address. The agent, following the injected instruction, uses its legitimate email scope to execute the exfiltration. The email API sees a valid token with the correct scope and complies. The attack succeeded not because the attacker broke the authentication model, but because the agent was given permissions broad enough to be weaponized.',
        '!! Okta\'s approach to mitigating confused deputy attacks operates at two levels. Fine Grained Authorization makes authorization decisions at the resource level, not just the scope level — meaning the agent cannot access specific records, mailboxes, or data stores it was not explicitly granted, even if it has a scope that nominally covers that resource class. Scoped tokens issued via Token Exchange limit the blast radius of any individual tool call to the permissions needed for that specific call. A confused deputy attack requires that the agent have permissions broad enough to be misused; Okta\'s minimal-privilege token model systematically narrows those permissions to the minimum needed for each discrete action.',
      ],
    },
    {
      heading: 'Prompt Injection and Token Leakage',
      paragraphs: [
        'Prompt injection is the AI agent equivalent of SQL injection — an attacker embeds instructions in content the agent is expected to process, causing the agent to execute those instructions as if they were legitimate commands from its principal. The attack surface is broad because agents are designed to be helpful and to act on the content they encounter: a webpage they browse, a document they summarize, a database record they retrieve, a customer support ticket they read. Any of these can contain injected instructions. Unlike SQL injection, which targets a well-defined query structure, prompt injection exploits the open-ended nature of language model instruction-following and is substantially harder to sanitize away entirely.',
        '!! The intersection of prompt injection and token management creates the token leakage risk. If an AI agent stores access tokens in its context window — the working memory available to the language model — or in an external memory store that the agent can read and write, then a successful prompt injection attack can cause the agent to exfiltrate those tokens. An attacker who obtains a long-lived, broad-scope token can use it to access APIs directly, bypassing the agent entirely. The longer the token lifetime and the broader the scope, the greater the damage from a single leakage event. This is why storing tokens in agent memory is categorically the wrong architecture for agentic systems.',
        'The mitigation stack for prompt injection and token leakage has three layers. First, just-in-time scoped tokens through the Token Vault pattern: tokens are never stored in the agent\'s context window or memory store — they are requested on demand for each tool call, used once, and expired. A prompt injection attack that attempts to read a token from memory finds nothing. Second, input validation and content sandboxing: agent systems should treat external content as untrusted input and apply appropriate sanitization, though this is a defense-in-depth measure rather than a complete solution. Third, human-in-the-loop gates for high-impact actions: actions that are irreversible, involve sensitive data, or exceed a risk threshold require explicit human confirmation before execution. The combination of these three layers does not make prompt injection impossible, but it makes the blast radius of a successful attack dramatically smaller.',
      ],
    },
    {
      heading: 'Minimal Privilege in Agentic Systems',
      paragraphs: [
        'The minimal privilege principle — every entity should have only the permissions needed for its current task — is straightforward to state and difficult to implement in agentic systems. The difficulty comes from the mismatch between how traditional OAuth scopes work and how AI agents operate. Traditional OAuth issues scopes at login time: a user authenticates, consents to a set of scopes, and receives a token that carries those scopes for the duration of the session. The agent then uses that same token for every action it takes, regardless of what specific action is occurring. This means the agent carries the maximum permissions it might ever need throughout its entire execution — the opposite of minimal privilege.',
        'Why this is harder to implement than it sounds in practice: the minimal privilege principle for agents requires per-call scope management, which means issuing a new, narrowly scoped token for each discrete tool call rather than using a session token. Traditional OAuth implementations do not support this — the token exchange grant type (RFC 8693) is not universally implemented, and there is no standard mechanism for dynamically narrowing scopes for individual calls within an existing session. Organizations that recognize the minimal privilege problem frequently conclude that implementing it correctly requires significant custom engineering work, and many defer or skip it entirely.',
        'TT Okta enables per-call minimal privilege through three integrated mechanisms. Token Exchange (RFC 8693) can issue a new token for each tool call with a narrower audience and scope tailored to that specific call — the orchestrator holds a broad delegation from the user but exchanges it for a narrow tool-specific token at the moment of invocation. Token Vault manages the lifecycle of these short-lived tokens, ensuring they are created on demand and expired promptly after use rather than accumulating in memory. Fine Grained Authorization provides the per-resource enforcement layer, ensuring that even a valid scoped token cannot access resources outside the specific grant — closing the gap between "has the right scope" and "has access to this specific record." The SE framing is direct: minimal privilege is a compliance requirement, not just a security best practice, and Okta gives organizations the technical mechanism to implement it at scale without building it from scratch.',
      ],
    },
  ],
};
