import type { SectionContent } from '../types';

export const content: SectionContent = {
  slug: 'why-okta',
  title: 'Why Okta',
  description:
    'The case for Okta as the identity platform for AI agentic systems — why rolling your own falls short, what differentiates Okta from alternatives, and the discovery questions that open the conversation.',
  tags: ['positioning', 'differentiation', 'discovery', 'competitive', 'se-enablement'],
  icon: '⚡',
  hasDiagram: false,
  diagramPrompt: '',
  cards: [
    {
      heading: 'Why Not Roll Your Own?',
      paragraphs: [
        'What "rolling your own" agent authentication actually requires is a useful exercise to walk through with a prospect. Implementing RFC 8693 token exchange correctly — including the audience and scope narrowing mechanics, the subject token validation, and the actor claim — is not a documentation-reading exercise; it requires deep OAuth implementation experience and careful handling of edge cases around token lifetimes, revocation propagation, and clock skew. Building per-resource authorization from scratch means implementing a relationship-based access control system that can evaluate "does agent A have permission to access resource B on behalf of user C" at low latency, at scale, and with a management interface that non-engineers can use. Token vault requires secure storage, rotation logic, audit logging, and integration with the agent runtime. Wiring audit logs to identity events means correlating application-layer logs with authorization-layer events from multiple systems. Scaling all of this across many agents, many users, and many target APIs is the problem that makes the upfront build cost look modest in retrospect.',
        'What actually happens in practice when organizations skip this build is well-documented in security incident post-mortems. Development teams under schedule pressure default to service accounts — a single set of credentials shared across all agents, with permissions scoped to the broadest set of things any agent might need. Tokens issued this way are long-lived because rotation requires coordinating across multiple systems. Audit logging covers what the application did, not what was authorized at the identity layer. FGA is deferred to a future sprint that never arrives. The result is a set of AI deployments that work functionally but that carry substantial security debt — debt that surfaces not during development but during a security review, a compliance audit, or an incident investigation.',
        'The real cost of the roll-your-own approach is not the upfront engineering investment, which teams reliably underestimate. It is the maintenance burden as the OAuth ecosystem evolves, the security incidents that arise from implementation gaps, and the compliance exposure that becomes visible when auditors arrive and ask for the identity-layer audit trail. Each of these costs is difficult to quantify in advance and easy to rationalize away during planning. The framing for a prospect is not "do you want to spend engineering cycles on this?" but "when your compliance team asks how AI agents are authorized and audited, what is your answer today, and is that answer defensible to an auditor?"',
      ],
    },
    {
      heading: 'Key Differentiators vs. Alternatives',
      paragraphs: [
        'Service accounts are the most common alternative and the most important to address directly. A service account authenticates as itself — it presents credentials that identify the service, not the user the service is acting for. There is no user delegation model, which means there is no mechanism for a service account to carry a user\'s identity through to a downstream API, no per-resource FGA that enforces what the service can access on whose behalf, and no On-Behalf-Of token that binds the user\'s authorization to the agent\'s action. Service accounts also cannot be revoked per-user — revoking a service account disables the entire service, not a specific user\'s delegation. For organizations that need to ensure an AI agent\'s access is immediately revoked when an employee leaves or changes roles, service accounts provide no mechanism to implement this. Custom JWT assertions address some of these gaps but introduce new ones: non-standard token formats are not verifiable by third-party APIs that have not been specifically configured to accept them, there is no FGA layer, and there is no built-in audit trail at the identity layer.',
        'Other identity providers offering "agent auth" capabilities are at various stages of development and completeness. The critical comparison point is the integration of all the components needed to implement the full minimal-privilege, auditable, delegated-access model: OBO token exchange, FGA, token vault, and an MCP protocol adapter. Okta\'s MCP Adapter is the only enterprise-grade authentication layer built specifically for the Model Context Protocol, addressing the protocol-level authentication problem that organizations encounter when deploying MCP-based agent systems. Okta\'s OBO is generally available and production-tested. FGA is production-ready and running at scale in enterprise deployments. These are not roadmap items or beta features — they are shipping capabilities.',
        'Okta\'s unique position in the agentic identity market is the result of breadth and integration, not any single feature. No other enterprise identity platform has all of OBO GA, FGA at production scale, a managed token vault, and active development of MCP protocol integration — assembled and integrated rather than requiring custom wiring between separate systems. For organizations evaluating identity vendors for their AI strategy, the question is not "can this vendor do token exchange?" but "can this vendor give us the complete architecture for secure, auditable, minimal-privilege AI agent deployment — and is it available today?" The answer for Okta is yes on both counts. That combination is durable differentiation worth anchoring in the account plan.',
      ],
    },
    {
      heading: 'Top Discovery Questions',
      paragraphs: [
        'The question "How are your AI agents authenticating to internal APIs today — and how do you know each agent action is authorized by the right user?" surfaces two gaps simultaneously. The first is the authentication model: most organizations answer with "service accounts" or "API keys," neither of which carries user identity through to the API. The second is the authorization gap: "how do you know each action is authorized by the right user" is a question most organizations cannot answer with their current architecture because the token the agent presents does not encode which user authorized it. This question is most effective with security architects and platform engineers who have already thought about the authentication problem and are beginning to recognize that solving authentication without solving authorization still leaves a significant gap.',
        'The question "What happens when an employee leaves or loses their authorization — how do you ensure AI agents acting on their behalf lose access immediately?" forces the conversation about delegation lifecycle. With service accounts or shared tokens, revoking an individual user\'s AI agent access requires either revoking the entire service account — which disables the agent for all users — or tracking and rotating individual credentials manually. Neither is operationally sustainable at scale. With Okta OBO, the user\'s authorization is bound to the token at exchange time: when the user\'s session is revoked or their permissions are changed, subsequent token exchange requests for that user will fail. This question resonates strongly with HR-security integration conversations and with organizations that have experienced the practical problem of offboarding employees who had AI agents running on their behalf.',
        'The question "If your AI agents take an action that causes a compliance incident, how do you prove to an auditor exactly what the agent did, on whose behalf, and what it was authorized to do?" closes the audit loop. It is the question that makes the abstract compliance requirement concrete and personal. Most organizations discover when answering this question that their current answer is "we look at application logs" — and application logs are not the identity-layer record that compliance frameworks require. The gap this question surfaces is the missing tamper-proof record of the authorization decision itself. Okta\'s System Log is that record, and the value of surfacing this gap in discovery is that it makes the audit-reporting capability a requirement, not a feature.',
      ],
    },
  ],
};
