import type { SectionContent } from '../types';

export const content: SectionContent = {
  slug: 'xaa-deep-dive',
  title: 'XAA Deep Dive',
  description:
    'How Okta\'s Cross App Access protocol solves enterprise-governed machine-to-machine communication — the technical flow, the identity assertion mechanism, and how to demo it end-to-end.',
  tags: ['XAA', 'cross-app-access', 'ID-JAG', 'OAuth', 'enterprise', 'EA'],
  icon: '🔗',
  hasDiagram: true,
  diagramPrompt:
    'Three-party flow diagram: Requesting App on left, Identity Provider (IdP) in center highlighted in amber, Resource App on right. Arrows: 1-Requesting App authenticates to IdP, 2-IdP issues identity assertion, 3-Requesting App presents assertion to Resource App, 4-Resource App validates and issues access token. Warm cream background, flat technical style.',
  cards: [
    {
      heading: 'What is Cross App Access (XAA)?',
      paragraphs: [
        'Cross App Access (XAA) is a new protocol from Okta designed to give enterprise IT administrators centralized, policy-driven control over how applications — including AI agents — communicate with one another. The protocol addresses a structural gap in standard OAuth 2.0: because OAuth consent screens rely on individual users granting permissions, enterprises have historically had no effective way to regulate app-to-app or agent-to-app communication at the organizational level. A user can consent to an app accessing another app\'s data, but the IT admin has no visibility into that grant and no mechanism to revoke or audit it centrally.',
        'With AI agents increasingly acting as autonomous systems that communicate across enterprise applications — reading data from one system, writing results to another, triggering workflows across platforms — the absence of IT oversight over these connections becomes a material security and compliance risk. XAA closes this gap. Rather than relying on user consent to authorize cross-app communication, XAA lets enterprise IT admins create "managed connections" between registered applications. These connections define which app can reach which other app, under what conditions, and with what level of trust — entirely from the Admin Console, without requiring individual users to make that determination themselves.',
        'Technically, XAA works by introducing a new trust artifact: the Identity Assertion JWT, or ID-JAG. When a requesting app needs to access a resource app, it goes to Okta to obtain an ID-JAG — a short-lived, Okta-signed token that asserts user identity plus enterprise-level authorization. This is fundamentally different from a standard OAuth access token or a client credentials grant because the trust does not originate from a user consent screen. It originates from an IT admin\'s managed connection policy. The resource app validates the ID-JAG against Okta\'s public keys, and if the assertion is valid and the connection is authorized, it issues a scoped access token for the requesting app to use.',
        '!! XAA is currently available as a self-service Early Access feature. To enable it in any Okta org, navigate to Admin Console > Settings > Features > Early Access and toggle on "Cross App Access." No support ticket or account team enablement is required — any admin can activate it today and begin creating managed connections through the standard application configuration UI.',
      ],
    },
    {
      heading: 'The XAA / ID-JAG Technical Flow',
      paragraphs: [
        'The XAA flow is a four-step exchange that replaces ad-hoc cross-app trust with a verifiable, Okta-mediated chain of assertions. Understanding each step is important for positioning the protocol accurately — and for explaining to technical audiences why this is meaningfully different from existing approaches like client credentials or JWT bearer grants used without an identity layer.',
        'Step 1: The requesting app — typically an AI agent or an integration service — authenticates to Okta using the Client Credentials grant type. This establishes the app\'s machine identity with Okta. The app presents its client ID and client secret (or a signed JWT assertion if using private key JWT authentication). Okta validates the credential and confirms that this registered app has a valid managed connection to the target resource app. This step is the IT policy enforcement gate: if no managed connection exists between the two apps, the flow stops here.',
        'Step 2: Okta issues an Identity Assertion JWT — the ID-JAG. This is a short-lived, RS256-signed token with specific claims: the subject (sub) claim carries the user\'s identity that the requesting app is acting on behalf of, the audience (aud) claim identifies the resource app\'s authorization server, and the issuer (iss) claim is the Okta org. The ID-JAG is not an access token — it cannot be used directly to call the resource app\'s API. It is an assertion from Okta that says: "this requesting app is authorized by enterprise policy to act on behalf of this user when talking to this resource app." The signing key is Okta\'s JWKS-published key, so the resource app can verify it without any out-of-band coordination with the requesting app.',
        'Step 3: The requesting app presents the ID-JAG to the resource app\'s authorization server using the JWT Bearer grant type defined in RFC 7523. This is a standard OAuth 2.0 grant type — the requesting app sends the ID-JAG in the assertion parameter of a token request to the resource app\'s /token endpoint. The requesting app also includes the scopes it needs for its intended API calls. Critically, the requesting app is not asking for a trust grant from the resource app directly. It is presenting a credential that was issued by a mutually trusted third party — Okta — and relying on the resource app to validate that credential through Okta.',
        '!! Step 4: The resource app\'s authorization server validates the ID-JAG by fetching Okta\'s JWKS endpoint and verifying the token\'s signature. It checks the aud claim to confirm the assertion was issued for this specific resource app, the sub claim to establish user identity, and the expiry to reject stale assertions. If validation passes, the resource app issues a scoped access token to the requesting app. This access token is standard — it can be used as a Bearer token for the resource app\'s API calls. The entire validation chain runs through Okta: the resource app never directly trusts the requesting app. It trusts only Okta\'s signed assertion that the requesting app was authorized to make this connection. This is the architectural guarantee that makes XAA enterprise-grade: trust is delegated to the IdP, not bilaterally negotiated between applications.',
        'The practical result is that every cross-app connection in an enterprise — including all agent-to-app calls — is mediated by a Okta-signed identity assertion that IT admins authorized in advance. This means connections can be audited, reviewed, and revoked centrally. If an AI agent is decommissioned, the admin removes its managed connection in the Admin Console and the ID-JAG issuance stops immediately. No user consent screens to track down, no OAuth grants scattered across user accounts, no service account passwords to rotate.',
      ],
    },
    {
      heading: 'Demo Setup and xaa.dev',
      paragraphs: [
        '!! For quick experimentation with XAA without any local environment setup, xaa.dev is a free browser-based playground launched in beta in January 2026. It lets you walk through the ID-JAG issuance and JWT Bearer exchange steps interactively, inspect the claims in each token, and understand the flow before committing to a full local demo. It is especially useful for technical discovery conversations where you want to show the protocol in action without requiring the prospect to configure anything.',
        'For a full, end-to-end local demo, the reference implementation lives in the oktadev/okta-secure-ai-agent-example GitHub repository. The setup is driven by a single bootstrap script: running pnpm run bootstrap:okta against a target Okta org automatically provisions all the required infrastructure. This includes a custom authorization server named "Todo MCP Authorization Server," three custom OAuth scopes (mcp:connect, mcp:tools:read, and mcp:tools:manage), two OIDC application registrations (Agent0 representing the AI agent and Todo0 representing the todo management API), an agent machine identity with an RSA key pair, a managed XAA connection between the two apps, and access policies that allow the JWT Bearer grant type. The script handles the entire org configuration in a single pass — there is no manual Admin Console work required after running it.',
        'The demo scenario has Agent0 — an AI agent powered by Claude via Amazon Bedrock — using XAA to access Todo0, a simple todo management API. The agent authenticates to Okta, receives an ID-JAG asserting the user\'s identity plus the managed connection authorization, presents that ID-JAG to Todo0\'s authorization server via RFC 7523 JWT Bearer grant, and receives a scoped token to call the todo API. The full flow is visible in browser developer tools and in the Okta system log, making it straightforward to show the complete trust chain during a demo.',
        '>> To enable XAA in any developer or sandbox Okta org before running the bootstrap script, go to Admin Console > Settings > Features > Early Access and turn on the "Cross App Access" toggle. This is a self-service activation — no feature flag request or support case needed. Once enabled, the managed connection UI appears under the application configuration for any registered app, and the ID-JAG issuance endpoint becomes available for testing.',
      ],
    },
  ],
};
